---

- hosts: all
  gather_facts: false
  remote_user: root
  tasks:

    - name: Ensure python-minimal is available
      apt:
        name: python-minimal
        allow_unauthenticated: yes

    - name: Ensure python-apt is available
      apt:
        name: python-apt
        allow_unauthenticated: yes

    - name: Ensure sudo is available
      apt:
        name: sudo
        allow_unauthenticated: yes

- hosts: zk
  remote_user: root
  handlers:
    - name: restart zookeeper
      service: name=zookeeper state=restarted

  tasks:
#    - name: Add Zookeeper package
#      apt:
#        name: zookeeper
#        state: present

    - debug:
        var: ansible_default_ipv4.address
    - debug:
        var: groups['zk']
    - debug:
        var: hostvars['ansible_default_ipv4'].address

    - name: Copy myid
      template: src=myid.j2 dest=/etc/zookeeper/conf/myid
      notify: restart zookeeper

    - name: Copy configuration
      template: src=zk.conf.j2 dest=/etc/zookeeper/conf/zoo.cfg
      notify: restart zookeeper
